<template class="">
  <div class="divisao-template ">
    <div class="p-5 text-center w-100 mx-auto first-division">
      <p class="bem-vindo-text scale-up-center">BEM VINDO!</p>
      <p class="introducao-texto">
        Está pronto para se aventurar pelas curiosidades do Geoparque?
      </p>
      <a href="#cracha" class="btn-lesgo">Vamos nessa!</a>
    </div>

    <div class="col-12 second-division" id="cracha">
      <div class="cordao-cracha"></div>
      <div class="cracha-body">
        <div class="cracha-content">
          <div class="cracha-header">
            <p class="text-visitante">CRACHA DE VISITANTE</p>
          </div>
          <div class="row d-flex">
            <div class="col-4">
              <img src="https://cdn-icons-png.flaticon.com/256/44/44948.png" class="img-fluid ms-5 p-3" width="150"
                alt="Foto do visitante" />
            </div>
            <div class="col-8 p-3">
              <div>
                <p class="h5">Nome do aventureiro:</p>
                <div>
                  <input type="text" class="cracha-input" v-model="nomeAventureiro" />
                </div>
              </div>
              <div class='mt-3'>
                <p class="h5">Setor: <span class="text-uppercase">PASSEIO</span></p>
              </div>
            </div>
          </div>
        </div>
        <div class="footer-cracha">
          <p class="text-center m-0 p-0">CÓDIGO 123847 - ÁREA DE ACESSO RESTRITA</p>
        </div>
      </div>
    </div>

    <div ontouchstart="" class="botao-continuar" @click="goToPuzzlePage">
      <div class="button">
        <a>Visitar</a>
      </div>
    </div>
  </div>
</template>
<script>
import TextTitleArcade from "@/components/TextTitleArcade/TextTitleArcade.vue";
import Swal from "sweetalert2";
export default {
  name: "Home",
  components: {
    TextTitleArcade,
  },
  async beforeMount() {
    Swal.fire({
      title: "Carregando...",
      allowOutsideClick: false,
      showConfirmButton: false,
      willOpen: () => {
        Swal.showLoading();
      },
    });
    const res = await this.$api().get("/puzzle").then((result) => {
              //sort puzzle
        const puzzles = result.data;
        const puzzle = puzzles[Math.floor(Math.random() * puzzles.length)];
        this.puzzleSorted = puzzle;
      Swal.close();
    }).catch((err) => {
      Swal.fire({
        icon: "error",
        title: "Erro ao carregar o puzzle",
        text: "Tente novamente mais tarde.",
      });
    });
  },
  methods: {
    async goToPuzzlePage() {
      //coloca nome em  maiusulo
      let nomeAventureiroMais = this.nomeAventureiro.toUpperCase();
        this.$router.push({ name: "PuzzlePage", params: { id: this.puzzleSorted.idPuzzle }, query: { name:nomeAventureiroMais , attempts: 0 }});
      //by name
    }, 
   },
  data() {
      return {
        i: 2,
        puzzleSorted: {},
        nomeAventureiro: "",
      };
    }
};
</script>
<style scoped>
/* ----------------------------------------------
 * Generated by Animista on 2024-6-1 23:18:18
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation scale-up-center
 * ----------------------------------------
 */
@-webkit-keyframes scale-up-center {
  0% {
    -webkit-transform: scale(0.5);
    transform: scale(0.5);
  }

  100% {
    -webkit-transform: scale(1);
    transform: scale(1);
  }
}

@keyframes scale-up-center {
  0% {
    -webkit-transform: scale(0.5);
    transform: scale(0.5);
  }

  100% {
    -webkit-transform: scale(1);
    transform: scale(1);
  }
}

.scale-up-center {
  -webkit-animation: scale-up-center 3s cubic-bezier(0.39, 0.575, 0.565, 1) both;
  animation: scale-up-center 3s cubic-bezier(0.39, 0.575, 0.565, 1) both;
}

.bem-vindo-text {
  font-size: 10rem;
  font-weight: bold;
  font-family: "ArcadeClassic", sans-serif;
  /* coloca como se tivesse um relevo em um branco clarinho */
  text-shadow: 5px 10px 5px #444444;
}

.cracha-input {
  width: 100%;
  height: 3rem;
  border-radius: 0.1rem;
  border: 1px solid #acacac;
  padding: 0.5rem;
  font-size: 1.5rem;
  font-weight: bold;
  text-transform: uppercase;
  margin-top: 0.4rem;
  background-color: white;
}

.button a {
  color: white;
  font-family: Helvetica, sans-serif;
  font-weight: bold;
  font-size: 36px;
  text-align: center;
  text-decoration: none;
  background-color: #2bff3d;
  display: block;
  position: relative;
  padding: 20px 40px;

  -webkit-tap-highlight-color: rgba(0, 0, 0, 0);
  text-shadow: 0px 1px 0px #000;
  filter: dropshadow(color=#000, offx=0px, offy=1px);

  -webkit-box-shadow: 0px 10px 0px #0b8a00;
  -moz-box-shadow: 0px 15px 0px #0b8a00;
  box-shadow: 0px 15px 0px #0b8a00;

  -webkit-border-radius: 5px;
  -moz-border-radius: 5px;
  border-radius: 5px;
}

.button a:active {
  top: 10px;
  background-color: #f78900;

  -webkit-box-shadow: inset 0 1px 0 #ffe5c4, inset 0 -3px 0 #915100;
  -moz-box-shadow: inset 0 1px 0 #ffe5c4, inset 0 -3pxpx 0 #915100;
  box-shadow: inset 0 1px 0 #ffe5c4, inset 0 -3px 0 #915100;
}

/* .button:after {
  content: "";
  height: 100%;
  width: 100%;
  padding: 4px;
  position: absolute;
  bottom: -15px;
  left: -4px;
  z-index: -1;
  background-color: #2b1800;
  -webkit-border-radius: 5px;
  -moz-border-radius: 5px;
  border-radius: 5px;
} */

.text-visitante {
  font-size: 1.8rem;
  font-weight: bold;
  /* deixa no meio */
  text-align: center;
  margin-top: 1.5rem;
}

.cracha-header {
  background-color: rgb(39, 102, 19);
  color: #fff;
  border-top-left-radius: 1rem;
  border-top-right-radius: 1rem;
  padding: 0.4rem;
}

.cordao-cracha {
  background-color: rgb(246, 250, 24);
  height: 300px;
  width: 10px;
  margin: 0 auto;
  position: relative;
  top: 0;
}

.cracha-body {
  background-color: #fff;
  height: 30vh;
  width: 40vw;
  color: #000;
  position: absolute;
  left: 30%;
  border-top-left-radius: 1.2rem;
  border-top-right-radius: 1.2rem;
  font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif
}

.cracha-content {
  display: flex;
  flex-direction: column;
}

.first-division {
  margin-top: 5rem;
  height: 50%;
  margin-bottom: 50%;
}

.second-division {
  height: 50%;

}

.botao-continuar {
  height: 3rem;
  position: relative;
  top: 35%;
  right: 0;
  width: 15rem;
  /* padding-bottom: 1000px; */
}

.footer-cracha {
  background-color: rgb(39, 102, 19);
  color: #fff;
  border-bottom-left-radius: 1rem;
  /* margin-top: 1.0rem; */
  border-bottom-right-radius: 1rem;
  padding: 0.4rem;
  height: 3rem;
}

.btn-lesgo {
  color: white;
  font-size: 1.5rem;
  font-weight: bold;
  padding: 1rem 2rem;
  border-radius: 0.5rem;
  text-decoration: none;

}

.divisao-template {
  display: flex;
  justify-content: space-between;
  flex-direction: column;
  align-items: center;

  height: 100vh;
}

.introducao-texto {
  font-size: 1.5rem;
  font-weight: bold;
  text-align: center;
  margin-top: 1.5rem;
}
</style>
